<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title }} | SalesDock</title>
    <link rel="icon" href="{{ asset('SalesDock.svg') }}" type="image/svg+xml">
    <style>
        :root { color-scheme: light; }
        * { box-sizing: border-box; }
        body { margin: 0; color: #111827; font: 14px/1.5 "Space Grotesk", "Segoe UI", sans-serif; background: #fff; }
        main { max-width: 920px; margin: 0 auto; padding: 1.75rem; }
        .brand {
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 1rem;
            padding-bottom: 1rem;
            margin-bottom: 1.25rem;
            border-bottom: 2px solid #16a34a;
        }
        .brand img { display: block; height: 42px; width: auto; }
        .brand strong { display: block; font-size: 1.05rem; }
        .brand span { color: #6b7280; font-size: 0.85rem; }
        header { display: flex; justify-content: space-between; gap: 1rem; margin-bottom: 1.25rem; }
        h1 { margin: 0 0 0.25rem; font-size: 1.45rem; }
        h2 { margin: 1.5rem 0 0.65rem; font-size: 1rem; }
        p { margin: 0.15rem 0; }
        .muted { color: #6b7280; }
        .meta { display: grid; gap: 0.2rem; text-align: right; font-size: 0.9rem; }
        .totals { display: grid; grid-template-columns: repeat(auto-fit, minmax(9rem, 1fr)); gap: 0.75rem; margin: 1rem 0 1.25rem; }
        .totals div { padding: 0.75rem; border: 1px solid #e5e7eb; border-radius: 0.75rem; }
        .totals span { display: block; color: #6b7280; font-size: 0.75rem; margin-bottom: 0.2rem; }
        .totals strong { font-size: 1rem; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 0.45rem 0.35rem; border-bottom: 1px solid #e5e7eb; text-align: left; font-size: 0.82rem; vertical-align: top; }
        th.num, td.num { text-align: right; white-space: nowrap; }
        .list { margin: 0; padding: 0; list-style: none; display: grid; gap: 0.45rem; }
        .list li { display: flex; justify-content: space-between; gap: 1rem; padding: 0.45rem 0; border-bottom: 1px solid #f3f4f6; }
        .actions { display: flex; gap: 0.75rem; margin-top: 1.5rem; }
        button, .btn {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            padding: 0.55rem 0.9rem;
            color: #fff;
            background: #16a34a;
            border: 0;
            border-radius: 0.45rem;
            font: inherit;
            font-weight: 600;
            text-decoration: none;
            cursor: pointer;
        }
        .btn.ghost { color: #111827; background: #fff; border: 1px solid #d1d5db; }
        .foot { margin-top: 1.5rem; padding-top: 0.85rem; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 0.8rem; }
        @media print {
            .actions { display: none; }
            main { padding: 0; max-width: none; }
        }
    </style>
</head>
<body>
    <main>
        <div class="brand">
            <img src="{{ asset('SalesDock.svg') }}" alt="SalesDock">
            <div style="text-align:right;">
                <strong>SalesDock report</strong>
                <span>{{ $generatedAt }}</span>
            </div>
        </div>

        <header>
            <div>
                <h1>{{ $title }}</h1>
                <p class="muted">{{ $range }}</p>
            </div>
            <div class="meta">
                <strong>{{ $businessName }}</strong>
                <span>Owner: {{ $ownerName }}</span>
                <span>Prepared by {{ $preparedBy }}</span>
            </div>
        </header>

        @yield('body')

        <p class="foot">Generated by SalesDock for {{ $businessName }} on {{ $generatedAt }}. Figures reflect completed ledger sales in the selected range.</p>

        <div class="actions">
            <button type="button" onclick="window.print()">Download / Print PDF</button>
            <a class="btn ghost" href="{{ $backUrl }}">Back</a>
        </div>
    </main>
    @if (request()->boolean('print'))
        <script>window.addEventListener('load', function () { window.print(); });</script>
    @endif
</body>
</html>
